server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        probability: 1
  cloud:
    #配置Nacos地址
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


#配置监控访问
management:
  endpoints:
    web:
      exposure:
        include: '*'

